import { type NextPage } from "next";
import Head from "next/head";
import TopVotes from "../components/topVotes/TopVotes";

const Home: NextPage = () => {
    //make this ssg and pass data to topvotes component
  return (
    <>
      <Head>
        <title>Final Fantasy Fanvote</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center max-w-7xl pt-8 md:pt-20 mt-4">
        <h1 className='text-white sm:text-2xl'>Final Fantasy Fanvote</h1>
        <TopVotes/>
      </main>
    </>
  );
};

export default Home;
