import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    
  return (
    <>
      <Head>
        <title>Final Fantasy Fanvote</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className='text-white'>Final Fantasy Fanvote</h1>
      </main>
    </>
  );
};

export default Home;
